### ISSUE TITLE
documentations and dependencies hipbone

### ISSUE THREAD

**Issue by kkordinia** [mateusmaso/hipbone#19]
@mateusmaso please provider a description about dependencies of hipbone.js and put this library doc.

**Comment by mateusmaso** [comment]
I'm sorry to say that this framework is no longer maintained by me. The only dependencies are [jQuery](/jquery/jquery), [Handlebars](/wycats/handlebars.js) and [Underscore](/jashkenas/underscore). If you're brave enough you can start messing around with the source code and the [TodoMVC example](/mateusmaso/hipbone/tree/master/examples/todomvc). If you are just starting a SPA app, I strongly recommend you having a look at more advanced libraries/frameworks such as [React](/facebook/react) and [Ember](/emberjs/ember.js).
